---
title: "Final Project"
author: "Zhe Huang"
date: "4/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
library(caret)
library(MASS)
library(gbm)
library(randomForest)
library(kernlab)
library(kableExtra)
```

```{r}
data = read.csv("Data_allfactors_khzl2.csv")
# Drop First 2 Columns
data_half_year = subset(data, select = -c(Unnamed..0, Period.Ending, VaR))
```

```{r}
inverse <- function(a) {
   ifelse(is.na(a), 0, 1/a)
}

data_half_year$Current.Ratio = inverse(data_half_year$Current.Ratio)
data_half_year$Quick.Ratio = inverse(data_half_year$Quick.Ratio)
```

```{r warning=FALSE}
################## Train Test Split #########################
# split the car data, train/test = 8/2

set.seed(2020)
data_idx = createDataPartition(data_half_year$half_year_return, p = 0.8, list = FALSE)
data_trn = data_half_year[data_idx, ]
data_tst = data_half_year[-data_idx, ]

################## Assumption Check for LR ####################
model = lm(half_year_return ~ ., data = data_trn)
par(mfrow = c(2,2))
plot(model)

################## AIC for Feature Selection ###################

model_init = lm(half_year_return ~ 1, data = data_trn)
aic_mod = stepAIC(
  model_init,
  direction = "both",
  scope = list(upper = model, lower = model_init),
  trace = 0
)

bic_mod = stepAIC(
  model_init,
  k = log(nrow(data_trn)),
  direction = "both",
  scope = list(upper = model, lower = model_init),
  trace = 0
)
```

```{r}
data_trn_aic = subset(data_trn, select = c(half_year_return, three_m_rtn, EY.CETOP, GICS.Sector, Liq.STOH, After.Tax.ROE, Liq.STOQ, Leverage.DTOA, non.linear.size, book.to.price))
```

```{r}
#KNN
set.seed(2020)

k_grid = expand.grid(k = seq(5, 50, 5))
mod_knn = train(
  half_year_return ~ .,
  data = data_trn_aic,
  trControl = trainControl(method = "cv", number = 5),
  method = "knn",
  tuneGrid = k_grid,
  preProcess = c("center", "scale")
)
```

```{r}
#Elastic Net
set.seed(2020)

mod_glmnet = train(
  half_year_return ~ .,
  data = data_trn_aic,
  trControl = trainControl(method = "cv", number = 5),
  method = "glmnet",
  tuneLength = 10
)
```

```{r}
#Gradient Boosting
set.seed(2020)

gbm_grid = expand.grid(interaction.depth = c(1, 2, 3),
                       n.trees = seq(30) * 100,
                       shrinkage = c(0.1, 0.3),
                       n.minobsinnode = c(10, 20))
mod_gbm = train(
  half_year_return ~ .,
  data = data_trn_aic,
  trControl = trainControl(method = "cv", number = 5),
  method = "gbm",
  tuneGrid = gbm_grid,
  verbose = FALSE
)
```

```{r}
#Random Forest
set.seed(2020)

mod_rf = train(
  half_year_return ~ .,
  data = data_trn_aic,
  trControl = trainControl(method = "cv", number = 5),
  method = "rf",
  tuneGrid = expand.grid(mtry = seq(1, ncol(data_trn_aic) - 1))
)
```

```{r}
#Support Vector Machine
set.seed(2020)

svm_grid = expand.grid(sigma = 10 ^ seq(-4, 2), C = 10 ^ seq(-3, 3))
mod_svm = train(
  half_year_return ~ .,
  data = data_trn_aic,
  trControl = trainControl(method = "cv", number = 5),
  method = "svmRadialSigma",
  tuneGrid = svm_grid
)
```

***

# Results

```{r}
get_rmse = function(actual, predicted) {
  sqrt(mean((actual - predicted) ^ 2))
}

get_best_result = function(caret_fit) {
  best = which(rownames(caret_fit$results) == rownames(caret_fit$bestTune))
  best_result = caret_fit$results[best, ]
  rownames(best_result) = NULL
  best_result
}
```

```{r}
cv_rmse = rep(0, 6)
cv_rmse[1] = get_rmse(data_trn$half_year_return, aic_mod$fitted.values)
mod_list = list(mod_knn, mod_glmnet, mod_gbm, mod_rf, mod_svm)
best_results = lapply(mod_list, get_best_result)
for (i in 1:5) {
  cv_rmse[i + 1] = best_results[[i]]$RMSE
}
```

```{r}
tst_mod_list = list(aic_mod, mod_knn, mod_glmnet, mod_gbm, mod_rf, mod_svm)
tst_pred = lapply(tst_mod_list, predict, newdata = data_tst)
tst_rmse = sapply(tst_pred, get_rmse, actual = data_tst$half_year_return)
```

```{r}
names = c("Linear regression", "K-nearest neighbors", "Elastic net", "Gradient boosting", "Random forest", "Support vector machine")
results = data.frame(names, cv_rmse, tst_rmse)
colnames(results) = c("Model", "Cross-Validated RMSE", "Test RMSE")
kable(results, "html", digits = 4) %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)
```

